name: qr_generator
description: "QR-Code Generator using qr_flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  barcode_widget:
  cupertino_icons: ^1.0.2
  image: ^4.1.3
  barcode_image: ^2.0.3
  path_provider: ^2.0.15
  gallery_saver: ^2.0.1
  flutter_svg: 2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  fonts:
  - family: NimbusSanL
    fonts:
      - asset: fonts/NimbusSanL-Reg.otf
      - asset: fonts/NimbusSanL-RegIta.otf
        style: italic
      - asset: fonts/NimbusSanL-Bol.otf
        weight: 700
      - asset: fonts/NimbusSanL-BolIta.otf
        weight: 700
        style: italic
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
      - asset: fonts/Poppins-SemiBold.ttf
        weight: 400
      - asset: fonts/Poppins-SemiBoldItalic.ttf
        weight: 400
        style: italic
      - asset: fonts/Poppins-Bold.ttf
        weight: 700
      - asset: fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Poppins-ExtraBold.ttf
        weight: 900
      - asset: fonts/Poppins-ExtraBoldItalic.ttf
        weight: 900
        style: italic